### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by stdevAlDen** [fibercrypto/FiberCryptoWallet#163]
**Describe the bug**
Going to Tools --> Outputs in the UI cause an unexpected exit of the application.

**Environment information:**

- OS: Linux
- Platform: Linux 5.2.0-2-amd64 x86_64
- Go: go version go1.12.9 linux/amd64

**Steps to Reproduce**

1. Run the application.
2. Go to Tools --> Outputs.
3. See error.

**Actual behavior**
Crash

**Expected behavior**
Show the outputs or notify an user for the user if any.

**Additional context**
```Get https://staging.node.skycoin.net/api/v1/csrf: dial tcp: lookup staging.node.skycoin.net on 127.0.0.1:53: no such host
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x9db64b]

goroutine 1 [running, locked to thread]:
github.com/fibercrypto/FiberCryptoWallet/src/models.(*ModelWallets).loadModel(0xc000275b30)
        /usr/share/gocode/src/github.com/fibercrypto/FiberCryptoWallet/src/models/modelWallets.go:114 +0xab
github.com/fibercrypto/FiberCryptoWallet/src/models.(*ModelWallets).init(0xc000275b30)
        /usr/share/gocode/src/github.com/fibercrypto/FiberCryptoWallet/src/models/modelWallets.go:47 +0x475
github.com/fibercrypto/FiberCryptoWallet/src/models.callbackModelWallets6f3c21_Constructor(0x4254cc0)
        /usr/share/gocode/src/github.com/fibercrypto/FiberCryptoWallet/src/models/moc.go:3089 +0x62
github.com/fibercrypto/FiberCryptoWallet/src/models._cgoexpwrap_7c260d073f8a_callbackModelWallets6f3c21_Constructor(0x4254cc0)
        _cgo_gotypes.go:22864 +0x2b
github.com/therecipe/qt/gui._Cfunc_QGuiApplication_QGuiApplication_Exec(0xc000000000)
        _cgo_gotypes.go:1360 +0x49
github.com/therecipe/qt/gui.(*QGuiApplication).Exec(...)
        /usr/share/gocode/src/github.com/therecipe/qt/gui/gui-minimal.go:1668
main.main()
        /usr/share/gocode/src/github.com/fibercrypto/FiberCryptoWallet/main.go:45 +0x20e
make: *** [Makefile:6: run] Error 2```

**Comment by stdevMac** [comment]
@stdevAlDen We are solving this in one PR

**Comment by olemis** [comment]
@stdevMac what PR ?

**Comment by stdevMac** [comment]
@olemis I am not completely sure, but the one for handling errors should solve ALL the crashes in the app

**Comment by stdevMac** [comment]
This should be solved with this PR => https://github.com/fibercrypto/FiberCryptoWallet/pull/153

**Comment by stdevMac** [comment]
This PR contains A proper error handling and also add a logger
