### ISSUE TITLE
App crash on startup

### ISSUE THREAD

**Issue by stdevAlDen** [fibercrypto/FiberCryptoWallet#187]
**Describe the bug**
Trying to open the application cause an unexpected exit.

**Environment information:**

- OS: Linux
- Platform: Linux 5.2.0-2-amd64 x86_64
- Go: go version go1.12.9 linux/amd64

**Steps to Reproduce**

1. `make run` (without a skycoin node running)
2. See error.

**Actual behavior**
Crash

**Expected behavior**
Show the application.

**Additional context**
```
[2019-10-29T12:55:07-04:00] ERROR [Skycoin Account]: Couldn't POST /api/v1/transactions?verbose=1 addrs="rspabT3fQVPa1bv3Z2fQFyw84gbEibjX3w" error="Get http://127.0.0.1:6420/api/v1/csrf: dial tcp 127.0.0.1:6420: connect: connection refused"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xc1b48b]

goroutine 1 [running, locked to thread]:
github.com/fibercrypto/FiberCryptoWallet/src/models/history.(*HistoryManager).getTransactionsOfAddresses(0xc000377200, 0xc00043c800, 0xb, 0x10, 0x9, 0xc00043c800, 0x8)
        github.com/fibercrypto/FiberCryptoWallet/src/models/history/historyManager.go:93 +0x3cb
github.com/fibercrypto/FiberCryptoWallet/src/models/history.(*HistoryManager).loadHistory(0xc000377200, 0x0, 0xc00040a700, 0x2edb390)
        github.com/fibercrypto/FiberCryptoWallet/src/models/history/historyManager.go:344 +0x1d1
github.com/fibercrypto/FiberCryptoWallet/src/models/history.callbackHistoryManager175bf8_LoadHistory.func1(0xc000254918, 0x2f03c50)
        github.com/fibercrypto/FiberCryptoWallet/src/models/history/moc.go:157 +0x61
github.com/fibercrypto/FiberCryptoWallet/src/models/history.callbackHistoryManager175bf8_LoadHistory(0x2f03c50, 0xc0000cdc88)
        github.com/fibercrypto/FiberCryptoWallet/src/models/history/moc.go:161 +0x5f
github.com/fibercrypto/FiberCryptoWallet/src/models/history._cgoexpwrap_da504d2b9cce_callbackHistoryManager175bf8_LoadHistory(0x2f03c50, 0x0)
        _cgo_gotypes.go:3083 +0x64
github.com/therecipe/qt/qml._Cfunc_QQmlApplicationEngine_Load(0x22d2890, 0x23751e0)
        _cgo_gotypes.go:921 +0x45
github.com/therecipe/qt/qml.(*QQmlApplicationEngine).Load.func1(0xc0002540d8, 0x104c560, 0xc0002540f0)
        github.com/therecipe/qt/qml/qml-minimal.go:792 +0xb4
github.com/therecipe/qt/qml.(*QQmlApplicationEngine).Load(0xc0002540d8, 0x104c560, 0xc0002540f0)
        github.com/therecipe/qt/qml/qml-minimal.go:792 +0x59
main.main()
        github.com/fibercrypto/FiberCryptoWallet/main.go:41 +0x1fc
make: *** [Makefile:14: run] Error 2
```

**Comment by stdevAlDen** [comment]
@stdevMac `config.json`:
```
{"SourceList":[{"Type":2,"Source":"/home/adacosta/.skycoin/wallets"}],"Node":"http://127.0.0.1:6420"}
```
