### ISSUE TITLE
Unexpected close loading wallet

### ISSUE THREAD

**Issue by stdevAlDen** [fibercrypto/FiberCryptoWallet#271]
**Describe the bug**
Having a list of deterministic wallets, taking the seed of one of them to load a bip44 wallet with this seed make the application to close unexpectedly.

**Environment information:**

- OS: GNU/Linux
- Platform: Linux 5.2.0-3-amd64 x86_64

**Steps to Reproduce**

1. Go to the application UI
2. Create a new deterministic wallet
3. Load a new bip44 wallet with the same seed as the previous.
4. See the stack trace...

**Actual behavior**
```
[2019-12-09T18:15:55-05:00] INFO [Skycoin Wallet]: Getting wallet set from wallet directory
[2019-12-09T18:15:55-05:00] INFO [Skycoin Wallet]: Getting Skycoin local wallet
[2019-12-09T18:15:55-05:00] ERROR [wallet]: Load: file.LoadJSON failed error="read /home/adacosta/.skycoin/wallets: is a directory" filename="/home/adacosta/.skycoin/wallets"
[2019-12-09T18:15:55-05:00] ERROR [Skycoin Wallet]: Call to wallet.Load(filename) inside GetWallet failed. error="read /home/adacosta/.skycoin/wallets: is a directory" filename="/home/adacosta/.skycoin/wallets"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xc3b624]

goroutine 1 [running, locked to thread]:
github.com/fibercrypto/fibercryptowallet/src/models.(*WalletManager).updateAddresses(0xc00022b900, 0x0, 0x0)
        github.com/fibercrypto/fibercryptowallet/src/models/walletsManager.go:137 +0x114
github.com/fibercrypto/fibercryptowallet/src/models.(*WalletManager).getAddresses(0xc00022b900, 0x0, 0x0, 0x5d0ef60, 0x1200000, 0xc000103c70)
        github.com/fibercrypto/fibercryptowallet/src/models/walletsManager.go:672 +0xa5
github.com/fibercrypto/fibercryptowallet/src/models.(*AddressesModel).updateModel(0xc00030c150, 0x0, 0x0)
        github.com/fibercrypto/fibercryptowallet/src/models/addressesModel.go:196 +0x41
github.com/fibercrypto/fibercryptowallet/src/models.callbackAddressesModel72d3a2_UpdateModel(0x5a566a0, 0x51bbb02, 0x0)
        github.com/fibercrypto/fibercryptowallet/src/models/moc.go:22987 +0xa1
github.com/fibercrypto/fibercryptowallet/src/models._cgoexpwrap_b6d9ad687100_callbackAddressesModel72d3a2_UpdateModel(0x5a566a0, 0x51bbb02, 0x0)
        _cgo_gotypes.go:35389 +0x3f
github.com/therecipe/qt/widgets._Cfunc_QApplication_QApplication_Exec(0xc000000000)
        _cgo_gotypes.go:1033 +0x49
github.com/therecipe/qt/widgets.(*QApplication).Exec(...)
        github.com/therecipe/qt/widgets/widgets-minimal.go:1009
main.main()
        github.com/fibercrypto/fibercryptowallet/main.go:60 +0x2ba
make: *** [Makefile:100: run] Error 2
```

**Expected behavior**
A new wallet should be loaded

**Comment by olemis** [comment]
@stdevAlDen schedule for v1 pls

**Comment by olemis** [comment]
@stdevAlDen if you still notice this happening feel free to reopen this issue
